"""P27 — the automated sweep controller: orchestrate a parameter sweep
across measurement lanes, driving a frozen protocol, honestly.

A single measurement point answers one question at one setting. A *sweep*
walks a parameter -- a drive frequency, a drive level, a temperature
setpoint, a specimen orientation -- across a grid (or a Cartesian product of
several), drives the frozen protocol at each point, and collects an
:class:`~r15.protocol_runner.ExperimentRun` per point. This module is that
controller, and like every other R15 module it is bounded by what the
environment can honestly produce.

**Reuse, not a new truth system.** The controller drives the P07 protocol
runner (:mod:`r15.protocol_runner`) at every point, so each point yields a
real ``ExperimentRun`` conforming to ``experiment_run.schema.json``; it
orders the sweep with the P08 randomization engine
(:mod:`r15.randomization`) so a randomized traversal is reproducible and
pre-committed; and it types every result through the governance core
(:mod:`r15.claims`). No parallel authority is invented.

**Five sweep strategies.** :class:`SweepStrategy` supports ``LINEAR``,
``LOGARITHMIC``, ``SPARSE``, ``RANDOMIZED`` and ``ADAPTIVE`` traversals. The
axis values are generated by :func:`linear_axis`, :func:`log_axis` or
:func:`sparse_axis`; ``RANDOMIZED`` permutes the traversal under a committed
seed (so the order is reproducible and tamper-evident, never chosen after
the data); ``ADAPTIVE`` refines toward a feature -- but only when the
refinement was **pre-declared** in the sealed plan.

**Four honest modes.** A ``SYNTHETIC`` sweep drives the runner's synthetic
simulator and is byte-identical under a seed. A ``REAL`` sweep runs nothing:
there is no bench, so every point is recorded ``PREREGISTERED_NOT_RUN`` with
no synthetic response. ``REPLAY`` and ``FAULT_INJECTION`` pass through to the
runner's corresponding modes. A synthetic response is never a measurement.

**No point is ever silently dropped.** Every planned point is recorded,
whatever happens to it: a point outside its axis's safety bounds is
``SAFETY_ABORTED`` (and never driven); a point whose dwell is shorter than
its settling requirement is ``SETTLING_NOT_REACHED``; a point whose drive
clips the response is ``CLIPPED_INVALID``. Each of those is kept in the
record, and :func:`refuse_dropped_points` refuses a record that is missing a
planned point. :func:`refuse_adaptive_as_cherrypicking` refuses adaptive
refinement that was not pre-declared in the sealed plan, because bisecting
toward a feature *after* seeing the data is cherry-picking, not refinement.

**Checkpoint and resume.** A partial :class:`SweepResult` can be handed back
to :meth:`SweepController.run` as ``resume_from``; already-recorded points
are carried through unchanged and only the remaining points are driven, so a
resumed sweep produces no duplicate evidence (no duplicate ``run_id``).

Nothing here is measured. The strongest class a synthetic sweep point
reaches is a ``SYNTHETIC_OBSERVATION``; a real sweep is
``PREREGISTERED_NOT_RUN``. ``measured_here = "nothing"`` and
``PHYSICAL_VALIDATION_NOT_CLAIMED``.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field, replace
from enum import Enum

import numpy as np

from r13 import serialize as r13_serialize
from r15 import claims as C
from r15 import protocol_runner as PR
from r15 import protocols as P
from r15 import randomization as RND


# =======================================================================
# Verdict, claim class, and the standing physical-validation disclaimer
# =======================================================================

VERDICT = "SWEEP_CONTROLLER_SYNTHETIC_NO_POINT_DROPPED_NO_POSTHOC_ADAPTIVE"
MEASURED_HERE = "nothing"
PHYSICAL_VALIDATION = "PHYSICAL_VALIDATION_NOT_CLAIMED"

#: The class of the controller machinery itself.
SOFTWARE_CLAIM_CLASS = C.ClaimClass.SOFTWARE_IMPLEMENTED
#: A synthetic sweep point's response is a SYNTHETIC_OBSERVATION.
POINT_CLAIM_CLASS = C.ClaimClass.SYNTHETIC_OBSERVATION
#: A physical sweep is preregistered, not run: no bench exists.
PHYSICAL_SWEEP_STATUS = "PREREGISTERED_NOT_RUN"

#: The version stamped onto every sweep record.
CONTROLLER_VERSION = "r15.sweeps/1.0"


class SweepError(RuntimeError):
    """Raised on any sweep-controller refusal or misuse.

    Covers the structural guards (an empty axis, an out-of-order safety
    band, an adaptive plan over more than one axis) and the load-bearing
    refusals (a dropped/omitted point, a post-hoc adaptive refinement that
    was not pre-declared in the sealed plan, a synthetic response read as a
    measurement).
    """


# =======================================================================
# Enumerations: the axis kinds, strategies, modes and point statuses
# =======================================================================

class SweepAxisKind(Enum):
    """The parameter a sweep axis walks."""

    FREQUENCY = "frequency_hz"
    DRIVE_LEVEL = "drive_level"
    TEMPERATURE_SETPOINT = "temperature_setpoint_k"
    ORIENTATION = "orientation_deg"


class SweepStrategy(Enum):
    """How the sweep points are generated and traversed."""

    LINEAR = "LINEAR"
    LOGARITHMIC = "LOGARITHMIC"
    SPARSE = "SPARSE"
    RANDOMIZED = "RANDOMIZED"
    ADAPTIVE = "ADAPTIVE"


class SweepMode(Enum):
    """The four sweep execution modes, kept strictly distinct.

    ``REAL`` is never executed here (no apparatus); ``SYNTHETIC`` drives the
    runner's seeded deterministic simulator; ``REPLAY`` re-emits recorded
    frames; ``FAULT_INJECTION`` injects a deterministic fault. Each maps onto
    the corresponding :class:`r15.protocol_runner.ExecutionMode`."""

    REAL = "REAL"
    SYNTHETIC = "SYNTHETIC"
    REPLAY = "REPLAY"
    FAULT_INJECTION = "FAULT_INJECTION"

    @property
    def execution_mode(self) -> PR.ExecutionMode:
        return PR.ExecutionMode[self.name]


class PointStatus(Enum):
    """The outcome of a single planned sweep point. Every planned point ends
    in exactly one of these -- none is ever dropped."""

    COLLECTED = "COLLECTED"
    SETTLING_NOT_REACHED = "SETTLING_NOT_REACHED"
    CLIPPED_INVALID = "CLIPPED_INVALID"
    SAFETY_ABORTED = "SAFETY_ABORTED"
    PREREGISTERED_NOT_RUN = "PREREGISTERED_NOT_RUN"


#: The point statuses whose response is a usable, valid observation.
VALID_STATUSES = frozenset({PointStatus.COLLECTED})


# =======================================================================
# Safety bounds and sweep axes
# =======================================================================

@dataclass(frozen=True)
class SafetyBounds:
    """An inclusive [lo, hi] band a swept parameter may not leave.

    A point whose value falls outside the band is refused -- the controller
    does not drive an out-of-bounds setting, it records the point as
    ``SAFETY_ABORTED``. Safety is checked before any acquisition."""

    lo: float
    hi: float

    def __post_init__(self) -> None:
        if not (math.isfinite(self.lo) and math.isfinite(self.hi)):
            raise SweepError("safety bounds must be finite")
        if self.hi < self.lo:
            raise SweepError("safety bounds must satisfy lo <= hi")

    def contains(self, value: float) -> bool:
        return self.lo <= float(value) <= self.hi


@dataclass(frozen=True)
class SweepAxis:
    """One axis of a sweep: a kind, its grid of values, a settling time and
    a safety band.

    ``settle_time_s`` is the dwell a point on this axis needs before its
    reading is trustworthy; a controller dwell shorter than this marks the
    point ``SETTLING_NOT_REACHED``. ``safety`` bounds the parameter; a value
    outside it is refused. The values are a frozen tuple so an axis is
    immutable and hashable."""

    kind: SweepAxisKind
    values: tuple
    unit: str = ""
    settle_time_s: float = 0.0
    safety: SafetyBounds | None = None

    def __post_init__(self) -> None:
        if not isinstance(self.kind, SweepAxisKind):
            raise SweepError("axis kind must be a SweepAxisKind")
        vals = tuple(float(v) for v in self.values)
        if len(vals) < 1:
            raise SweepError("a sweep axis needs at least one value")
        if not all(math.isfinite(v) for v in vals):
            raise SweepError("axis values must be finite")
        if self.settle_time_s < 0.0:
            raise SweepError("settle_time_s must be non-negative")
        object.__setattr__(self, "values", vals)

    def within_safety(self, value: float) -> bool:
        return self.safety is None or self.safety.contains(value)

    def to_spec(self) -> dict:
        spec = {
            "kind": self.kind.value,
            "values": [float(v) for v in self.values],
            "unit": self.unit,
            "settle_time_s": float(self.settle_time_s),
        }
        if self.safety is not None:
            spec["safety"] = {"lo": float(self.safety.lo),
                              "hi": float(self.safety.hi)}
        return spec


# --- axis generators ------------------------------------------------------

def linear_axis(kind: SweepAxisKind, start: float, stop: float, n: int,
                *, unit: str = "", settle_time_s: float = 0.0,
                safety: SafetyBounds | None = None) -> SweepAxis:
    """A linearly spaced axis of ``n`` points on ``[start, stop]``."""
    if int(n) < 1:
        raise SweepError("a linear axis needs at least one point")
    vals = np.linspace(float(start), float(stop), int(n))
    return SweepAxis(kind, tuple(float(v) for v in vals), unit=unit,
                     settle_time_s=settle_time_s, safety=safety)


def log_axis(kind: SweepAxisKind, start: float, stop: float, n: int,
             *, unit: str = "", settle_time_s: float = 0.0,
             safety: SafetyBounds | None = None) -> SweepAxis:
    """A logarithmically spaced axis of ``n`` points on ``[start, stop]``.

    Both endpoints must be strictly positive -- a decade grid is undefined
    through zero -- so a non-positive endpoint is refused rather than folded
    into a NaN."""
    if int(n) < 1:
        raise SweepError("a log axis needs at least one point")
    if float(start) <= 0.0 or float(stop) <= 0.0:
        raise SweepError(
            "a logarithmic axis needs strictly positive endpoints")
    vals = np.logspace(math.log10(float(start)), math.log10(float(stop)),
                       int(n))
    return SweepAxis(kind, tuple(float(v) for v in vals), unit=unit,
                     settle_time_s=settle_time_s, safety=safety)


def sparse_axis(kind: SweepAxisKind, values, *, unit: str = "",
                settle_time_s: float = 0.0,
                safety: SafetyBounds | None = None) -> SweepAxis:
    """A sparse axis: an explicit, arbitrary set of values (sorted, unique)."""
    uniq = sorted({float(v) for v in values})
    if not uniq:
        raise SweepError("a sparse axis needs at least one value")
    return SweepAxis(kind, tuple(uniq), unit=unit,
                     settle_time_s=settle_time_s, safety=safety)


# =======================================================================
# The adaptive-refinement policy (must be pre-declared in the sealed plan)
# =======================================================================

@dataclass(frozen=True)
class AdaptivePolicy:
    """A pre-declared adaptive-refinement policy.

    Adaptive refinement -- bisecting toward a feature such as a resonance --
    is legitimate only when it is declared *before* the sweep runs and sealed
    into the plan. A policy carries the axis it refines, how many refinement
    evaluations it may spend, the objective, and a convergence tolerance. The
    ``pre_declared`` flag is the honesty bit: refinement without it is
    post-hoc cherry-picking and is refused."""

    axis: SweepAxisKind
    max_refinements: int = 8
    objective: str = "MAXIMIZE_RESPONSE"
    tolerance: float = 0.0
    pre_declared: bool = True

    def __post_init__(self) -> None:
        if not isinstance(self.axis, SweepAxisKind):
            raise SweepError("adaptive axis must be a SweepAxisKind")
        if int(self.max_refinements) < 1:
            raise SweepError("max_refinements must be >= 1")
        if self.objective != "MAXIMIZE_RESPONSE":
            raise SweepError(
                f"unsupported adaptive objective {self.objective!r}; only "
                f"MAXIMIZE_RESPONSE is implemented")

    def to_spec(self) -> dict:
        return {
            "axis": self.axis.value,
            "max_refinements": int(self.max_refinements),
            "objective": self.objective,
            "tolerance": float(self.tolerance),
            "pre_declared": bool(self.pre_declared),
        }


# =======================================================================
# The sweep plan and its seal
# =======================================================================

@dataclass(frozen=True)
class SweepPlan:
    """A frozen plan for a parameter sweep.

    The points are the Cartesian product of the axes' values, taken in axis
    order. ``strategy`` documents how the grid was built and traversed;
    ``mode`` selects the execution mode; ``seed`` makes a synthetic sweep and
    a randomized traversal reproducible; ``dwell_s`` is the settling dwell
    spent at each point. ``adaptive`` is the pre-declared refinement policy
    (or ``None``). ``lanes`` names the measurement lanes the sweep drives, for
    the record. A plan is sealed with :func:`freeze` before it runs."""

    plan_id: str
    axes: tuple
    strategy: SweepStrategy
    mode: SweepMode
    seed: int
    dwell_s: float = 1.0
    adaptive: AdaptivePolicy | None = None
    lanes: tuple = ()

    def __post_init__(self) -> None:
        if not self.axes:
            raise SweepError("a sweep plan needs at least one axis")
        if not all(isinstance(a, SweepAxis) for a in self.axes):
            raise SweepError("every axis must be a SweepAxis")
        if not isinstance(self.strategy, SweepStrategy):
            raise SweepError("strategy must be a SweepStrategy")
        if not isinstance(self.mode, SweepMode):
            raise SweepError("mode must be a SweepMode")
        if self.dwell_s < 0.0:
            raise SweepError("dwell_s must be non-negative")
        if self.strategy is SweepStrategy.ADAPTIVE and self.adaptive is None:
            raise SweepError(
                "an ADAPTIVE strategy needs a pre-declared AdaptivePolicy; "
                "adaptive refinement must be declared before the sweep runs")
        if self.adaptive is not None:
            if len(self.axes) != 1:
                raise SweepError(
                    "adaptive refinement is defined over a single continuous "
                    "axis; provide exactly one axis when adaptive is set")
            if self.axes[0].kind is not self.adaptive.axis:
                raise SweepError(
                    "the adaptive policy axis must match the plan's axis")

    @property
    def axis_kinds(self) -> tuple:
        return tuple(a.kind for a in self.axes)

    def base_points(self) -> tuple:
        """The Cartesian product of the axes, as ordered :class:`SweepPoint`s.

        Product order is axis order (the first axis varies slowest), then the
        traversal is reordered by :meth:`ordered_points`."""
        grids = [a.values for a in self.axes]
        kinds = [a.kind for a in self.axes]
        points: list[SweepPoint] = []
        idx = 0
        for combo in _cartesian(grids):
            params = {kinds[i].value: float(combo[i])
                      for i in range(len(kinds))}
            points.append(SweepPoint(index=idx, params=params, phase="base"))
            idx += 1
        return tuple(points)

    def ordered_points(self) -> tuple:
        """The base points in traversal order.

        For every strategy but ``RANDOMIZED`` the order is the natural
        product order. ``RANDOMIZED`` permutes the indices with the P08
        randomization engine under the plan seed, so the order is reproducible
        and pre-committed -- it cannot be chosen after seeing the data."""
        pts = self.base_points()
        if self.strategy is SweepStrategy.RANDOMIZED:
            order = RND.randomize(tuple(range(len(pts))),
                                  RND.derive_seed(self.seed, "sweep_order"))
            return tuple(pts[i] for i in order)
        return pts

    def spec(self) -> dict:
        """A canonical, JSON-friendly spec of the plan (for the seal)."""
        return {
            "plan_id": self.plan_id,
            "axes": [a.to_spec() for a in self.axes],
            "strategy": self.strategy.value,
            "mode": self.mode.value,
            "seed": int(self.seed),
            "dwell_s": float(self.dwell_s),
            "adaptive": self.adaptive.to_spec() if self.adaptive else None,
            "lanes": list(self.lanes),
            "controller_version": CONTROLLER_VERSION,
        }

    def plan_hash(self) -> str:
        """A stable content hash of the plan spec (reuses R13 serialize)."""
        return r13_serialize.content_hash(self.spec())


@dataclass(frozen=True)
class SealedSweepPlan:
    """A sweep plan sealed before it runs.

    Carries the plan, a seal (the plan hash at freeze time) and the epoch it
    was sealed at. :meth:`verify` recomputes the hash and detects an edit
    after the seal -- a plan changed after freezing may not run under the old
    seal."""

    plan: SweepPlan
    seal: str
    sealed_epoch: int

    def verify(self) -> bool:
        return self.plan.plan_hash() == self.seal


def freeze(plan: SweepPlan, *, epoch: int) -> SealedSweepPlan:
    """Seal a sweep plan by committing its content hash at ``epoch``."""
    if not isinstance(plan, SweepPlan):
        raise SweepError("freeze expects a SweepPlan")
    return SealedSweepPlan(plan=plan, seal=plan.plan_hash(),
                           sealed_epoch=int(epoch))


def _cartesian(grids):
    """Yield the Cartesian product of a list of value tuples, first slowest."""
    if not grids:
        yield ()
        return
    head, *rest = grids
    for v in head:
        for tail in _cartesian(rest):
            yield (v,) + tail


# =======================================================================
# A sweep point and its result
# =======================================================================

@dataclass(frozen=True)
class SweepPoint:
    """One planned point in the sweep: an index, its parameter dict, and
    whether it is a ``base`` grid point or an adaptive ``refine`` point."""

    index: int
    params: dict
    phase: str = "base"

    def value_on(self, kind: SweepAxisKind) -> float:
        return float(self.params[kind.value])


@dataclass(frozen=True)
class ResponseSample:
    """A deterministic synthetic response at one sweep point.

    ``value`` is the modelled response; ``clipped`` marks a drive that
    saturated the response (an invalid step); ``claim_class`` is a
    ``SYNTHETIC_OBSERVATION`` and never a measurement class."""

    value: float
    clipped: bool
    claim_class: str = POINT_CLAIM_CLASS.value

    def as_dict(self) -> dict:
        return {"value": float(self.value), "clipped": bool(self.clipped),
                "claim_class": self.claim_class,
                "measured_here": MEASURED_HERE}


@dataclass(frozen=True)
class SweepPointResult:
    """The record of one attempted sweep point -- always kept.

    Carries the point, the run id, the point status, whether it settled and
    clipped, the synthetic response (``None`` for a safety-aborted or a real
    point), and the ``ExperimentRun`` record the runner produced (``None``
    when the point was not driven). No point result is ever discarded."""

    point_index: int
    run_id: str
    phase: str
    params: dict
    status: PointStatus
    settled: bool
    clipped: bool
    response: ResponseSample | None
    experiment_run: dict | None

    @property
    def is_valid(self) -> bool:
        return self.status in VALID_STATUSES

    def to_record(self) -> dict:
        return {
            "point_index": int(self.point_index),
            "run_id": self.run_id,
            "phase": self.phase,
            "params": dict(self.params),
            "status": self.status.value,
            "settled": bool(self.settled),
            "clipped": bool(self.clipped),
            "response": self.response.as_dict() if self.response else None,
            "experiment_run": self.experiment_run,
        }


@dataclass(frozen=True)
class SweepResult:
    """The full record of a sweep: every point, in traversal order.

    ``feature_estimate`` is the (parameter value, response) of the strongest
    valid point along the adaptive axis, or ``None`` when nothing valid was
    collected. ``n_planned`` is the number of base points; ``points`` also
    includes any adaptive refinement points. No planned point is missing --
    :func:`refuse_dropped_points` is asserted before the result is returned."""

    plan_id: str
    seal: str
    mode: str
    strategy: str
    n_planned: int
    points: tuple
    feature_estimate: dict | None

    def status_counts(self) -> dict:
        counts: dict = {}
        for r in self.points:
            counts[r.status.value] = counts.get(r.status.value, 0) + 1
        return counts

    def valid_points(self) -> tuple:
        return tuple(r for r in self.points if r.is_valid)

    def run_ids(self) -> tuple:
        return tuple(r.run_id for r in self.points)

    def base_results(self) -> tuple:
        return tuple(r for r in self.points if r.phase == "base")

    def to_record(self) -> dict:
        return {
            "plan_id": self.plan_id,
            "seal": self.seal,
            "mode": self.mode,
            "strategy": self.strategy,
            "controller_version": CONTROLLER_VERSION,
            "n_planned": int(self.n_planned),
            "n_recorded": len(self.points),
            "status_counts": self.status_counts(),
            "feature_estimate": self.feature_estimate,
            "points": [r.to_record() for r in self.points],
            "claim_class": POINT_CLAIM_CLASS.value,
            "measured_here": MEASURED_HERE,
            "physical_validation": PHYSICAL_VALIDATION,
        }


# =======================================================================
# The synthetic response model (deterministic; plants a feature)
# =======================================================================

@dataclass(frozen=True)
class PlantedFeature:
    """A feature planted in the synthetic response: a Lorentzian resonance in
    frequency, centred at ``center_hz`` with half-width ``width_hz`` and peak
    ``height``.

    A synthetic feature, not a specimen resonance. The controller's adaptive
    refinement recovers this planted centre; recovering a number this module
    planted is never a measurement of a real resonance."""

    center_hz: float
    width_hz: float
    height: float = 1.0

    def __post_init__(self) -> None:
        if self.width_hz <= 0.0 or not math.isfinite(self.width_hz):
            raise SweepError("a planted feature needs a positive width")
        if self.center_hz <= 0.0:
            raise SweepError("a planted feature needs a positive centre")

    def lorentzian(self, frequency_hz: float) -> float:
        d = (float(frequency_hz) - self.center_hz) / self.width_hz
        return float(self.height) / (1.0 + d * d)


@dataclass(frozen=True)
class SyntheticResponseModel:
    """A deterministic model of a swept response with a planted feature.

    The response is the planted Lorentzian in frequency, scaled by the drive
    level and shifted by any temperature offset, plus a tiny seeded noise. A
    drive above ``drive_clip_level`` saturates the response: the sample is
    flagged ``clipped`` and pinned at ``clip_value`` -- a clipped step is
    invalid. Everything is a pure function of the parameters and the seed:
    the same point always yields the same response."""

    feature: PlantedFeature
    reference_temperature_k: float = 300.0
    temperature_coefficient: float = 0.0
    drive_clip_level: float = 5.0
    clip_value: float = 1.0e3
    noise: float = 1.0e-6
    baseline: float = 0.0

    def response(self, params: dict, seed: int) -> ResponseSample:
        freq = float(params.get(SweepAxisKind.FREQUENCY.value,
                                self.feature.center_hz))
        drive = float(params.get(SweepAxisKind.DRIVE_LEVEL.value, 1.0))
        temp = float(params.get(SweepAxisKind.TEMPERATURE_SETPOINT.value,
                                self.reference_temperature_k))
        center = self.feature.center_hz * (
            1.0 + self.temperature_coefficient
            * (temp - self.reference_temperature_k))
        d = (freq - center) / self.feature.width_hz
        peak = float(self.feature.height) / (1.0 + d * d)
        amp = drive * peak + self.baseline
        clipped = drive > self.drive_clip_level or amp > self.clip_value
        # Deterministic per-point noise, a pure function of (params, seed).
        digest = r13_serialize.content_hash(
            {"params": {k: float(v) for k, v in sorted(params.items())},
             "seed": int(seed)})
        rng = np.random.default_rng(int(digest[:16], 16))
        value = amp + float(self.noise) * float(rng.standard_normal())
        if clipped:
            value = float(self.clip_value)
        return ResponseSample(value=value, clipped=bool(clipped))


# =======================================================================
# The controller
# =======================================================================

class SweepController:
    """The automated sweep controller.

    Drives a sealed sweep plan against a frozen protocol, one point at a
    time, collecting an :class:`~r15.protocol_runner.ExperimentRun` per point
    and (for a synthetic sweep) a deterministic response sample. Enforces the
    settling, safety-bound and clipping policies, records every planned point
    whatever its outcome, refines adaptively only when the plan pre-declared
    it, and supports checkpoint/resume without duplicating evidence."""

    def __init__(self, sealed_plan: SealedSweepPlan,
                 sealed_protocol: P.SealedProtocol,
                 base_config: PR.RunConfig,
                 response_model: SyntheticResponseModel | None = None) -> None:
        if not isinstance(sealed_plan, SealedSweepPlan):
            raise SweepError("sealed_plan must be a SealedSweepPlan")
        if not sealed_plan.verify():
            raise SweepError(
                "refused: the sweep plan seal is broken; a plan edited after "
                "freezing may not run under the old seal")
        if not isinstance(base_config, PR.RunConfig):
            raise SweepError("base_config must be a RunConfig")
        self.sealed_plan = sealed_plan
        self.plan = sealed_plan.plan
        self.sealed_protocol = sealed_protocol
        self.base_config = base_config
        self.model = response_model

    # --- settling ------------------------------------------------------

    def _settle_required(self) -> float:
        """The dwell a point needs: the longest axis settling time."""
        return max((a.settle_time_s for a in self.plan.axes), default=0.0)

    def _settled(self) -> bool:
        return self.plan.dwell_s >= self._settle_required()

    # --- safety --------------------------------------------------------

    def _within_safety(self, point: SweepPoint) -> bool:
        for axis in self.plan.axes:
            if axis.kind.value in point.params:
                if not axis.within_safety(point.params[axis.kind.value]):
                    return False
        return True

    # --- one point -----------------------------------------------------

    def _run_id(self, point: SweepPoint) -> str:
        tag = "R" if point.phase == "refine" else "P"
        return f"{self.plan.plan_id}-{tag}{point.index:04d}"

    def _drive_point(self, point: SweepPoint, epoch: int,
                     mode: PR.ExecutionMode) -> dict:
        """Drive the frozen protocol at one point, returning the run record."""
        cfg = replace(
            self.base_config, mode=mode,
            seed=int(self.base_config.seed) + int(point.index),
            environment={**dict(self.base_config.environment), **point.params,
                         "sweep_plan_id": self.plan.plan_id,
                         "sweep_point_index": int(point.index)})
        run = PR.execute(self.sealed_protocol, cfg,
                         run_id=self._run_id(point), epoch=int(epoch))
        return run.to_record()

    def _run_point(self, point: SweepPoint, epoch: int) -> SweepPointResult:
        """Run one point under the plan's mode, recording it whatever happens."""
        run_id = self._run_id(point)

        # A real sweep runs nothing: the point is preregistered, not run.
        if self.plan.mode is SweepMode.REAL:
            run_rec = self._drive_point(point, epoch, PR.ExecutionMode.REAL)
            return SweepPointResult(
                point_index=point.index, run_id=run_id, phase=point.phase,
                params=dict(point.params),
                status=PointStatus.PREREGISTERED_NOT_RUN,
                settled=False, clipped=False, response=None,
                experiment_run=run_rec)

        # Safety: an out-of-bounds setting is never driven.
        if not self._within_safety(point):
            return SweepPointResult(
                point_index=point.index, run_id=run_id, phase=point.phase,
                params=dict(point.params), status=PointStatus.SAFETY_ABORTED,
                settled=False, clipped=False, response=None,
                experiment_run=None)

        # Drive the protocol (produces the ExperimentRun) and model the
        # response.
        run_rec = self._drive_point(point, epoch, self.plan.mode.execution_mode)
        sample = None
        if self.model is not None:
            sample = self.model.response(point.params,
                                         int(self.base_config.seed))
        settled = self._settled()
        clipped = bool(sample.clipped) if sample is not None else False

        if clipped:
            status = PointStatus.CLIPPED_INVALID
        elif not settled:
            status = PointStatus.SETTLING_NOT_REACHED
        else:
            status = PointStatus.COLLECTED
        return SweepPointResult(
            point_index=point.index, run_id=run_id, phase=point.phase,
            params=dict(point.params), status=status, settled=settled,
            clipped=clipped, response=sample, experiment_run=run_rec)

    # --- adaptive refinement (only if pre-declared) --------------------

    def _adaptive_refine(self, base_results, epoch: int,
                         start_index: int) -> list:
        """Bisect toward the strongest valid base point (ternary search).

        Runs ONLY when the sealed plan pre-declared an :class:`AdaptivePolicy`.
        Uses the valid base points along the adaptive axis to bracket the
        maximum, then narrows the bracket by ternary search, evaluating a new
        refinement point per step. Converges to the planted feature for a
        unimodal response."""
        policy = self.plan.adaptive
        refuse_adaptive_as_cherrypicking(policy)
        axis = policy.axis
        valid = [r for r in base_results if r.is_valid and r.response
                 is not None]
        if len(valid) < 3:
            return []  # not enough bracket to refine
        valid.sort(key=lambda r: r.params[axis.value])
        vals = [r.params[axis.value] for r in valid]
        resp = [r.response.value for r in valid]
        peak = int(np.argmax(resp))
        lo_i = max(0, peak - 1)
        hi_i = min(len(vals) - 1, peak + 1)
        lo, hi = vals[lo_i], vals[hi_i]

        refined: list = []
        idx = int(start_index)
        for _ in range(int(policy.max_refinements)):
            if hi - lo <= policy.tolerance:
                break
            m1 = lo + (hi - lo) / 3.0
            m2 = hi - (hi - lo) / 3.0
            r1 = self._evaluate_refine_point(axis, m1, valid[peak], idx, epoch)
            idx += 1
            r2 = self._evaluate_refine_point(axis, m2, valid[peak], idx, epoch)
            idx += 1
            refined.extend([r1, r2])
            v1 = r1.response.value if r1.response else -math.inf
            v2 = r2.response.value if r2.response else -math.inf
            if v1 < v2:
                lo = m1
            else:
                hi = m2
        return refined

    def _evaluate_refine_point(self, axis: SweepAxisKind, value: float,
                               template: SweepPointResult, index: int,
                               epoch: int) -> SweepPointResult:
        params = dict(template.params)
        params[axis.value] = float(value)
        point = SweepPoint(index=index, params=params, phase="refine")
        return self._run_point(point, epoch)

    # --- the run -------------------------------------------------------

    def run(self, *, epoch: int, resume_from: SweepResult | None = None,
            max_points: int | None = None) -> SweepResult:
        """Run the sealed sweep, recording every planned point.

        ``resume_from`` carries the results of an interrupted sweep; already
        recorded base points are reused unchanged (no re-drive, no duplicate
        run id) and only the remaining points are driven. ``max_points`` stops
        the base traversal early (a checkpoint) -- the returned partial result
        can be handed back as ``resume_from``. Adaptive refinement runs only
        after the full base grid is complete and only if pre-declared."""
        if not self.sealed_plan.verify():
            raise SweepError(
                "refused: the sweep plan seal is broken; cannot run an edited "
                "plan under the old seal")

        ordered = self.plan.ordered_points()
        done: dict = {}
        if resume_from is not None:
            for r in resume_from.base_results():
                done[r.point_index] = r

        results: list = []
        driven = 0
        for point in ordered:
            if point.index in done:
                results.append(done[point.index])
                continue
            if max_points is not None and driven >= int(max_points):
                # Checkpoint: stop driving new points here.
                break
            results.append(self._run_point(point, epoch))
            driven += 1

        base_recorded = {r.point_index for r in results}
        planned = len(ordered)
        base_complete = len(base_recorded) == planned

        # Adaptive refinement only over a complete base grid, and only if the
        # plan pre-declared it. Never on a real sweep (nothing was measured).
        refined: list = []
        if (base_complete and self.plan.adaptive is not None
                and self.plan.mode is not SweepMode.REAL):
            refined = self._adaptive_refine(results, epoch,
                                            start_index=planned)

        all_results = results + refined

        # A complete run must contain every planned point -- no silent drops.
        if base_complete:
            refuse_dropped_points(range(planned),
                                  [r.point_index for r in results])

        feature = _feature_estimate(all_results, self.plan)
        return SweepResult(
            plan_id=self.plan.plan_id, seal=self.sealed_plan.seal,
            mode=self.plan.mode.value, strategy=self.plan.strategy.value,
            n_planned=planned, points=tuple(all_results),
            feature_estimate=feature)


def _feature_estimate(results, plan: SweepPlan) -> dict | None:
    """The (value, response) of the strongest valid point along the adaptive
    axis, or ``None`` when nothing valid was collected."""
    axis = plan.adaptive.axis if plan.adaptive else plan.axes[0].kind
    valid = [r for r in results if r.is_valid and r.response is not None]
    if not valid:
        return None
    best = max(valid, key=lambda r: r.response.value)
    return {
        "axis": axis.value,
        "value": float(best.params.get(axis.value, math.nan)),
        "response": float(best.response.value),
        "run_id": best.run_id,
        "phase": best.phase,
    }


# =======================================================================
# The load-bearing refusals
# =======================================================================

def refuse_adaptive_as_cherrypicking(policy) -> None:
    """Refuse adaptive refinement that was not pre-declared in the sealed
    plan. Raises.

    Bisecting toward a feature *after* the sweep has run and the data is in
    hand is cherry-picking: the operator would be choosing which points to
    add having already seen which region flatters the answer. Legitimate
    adaptive refinement is declared in the plan and sealed before the run, so
    its policy carries ``pre_declared=True``. A missing policy, or one whose
    ``pre_declared`` flag is not set, is refused here."""
    if policy is None:
        raise SweepError(
            "refused: adaptive refinement requested with no pre-declared "
            "AdaptivePolicy. Bisecting toward a feature after the data is in "
            "hand is cherry-picking. Declare the refinement in the plan and "
            "seal it BEFORE the sweep runs.")
    if not getattr(policy, "pre_declared", False):
        raise SweepError(
            "refused: the adaptive policy is not marked pre_declared. Adaptive "
            "refinement must be committed in the sealed plan before the run; a "
            "post-hoc refinement chosen after seeing the data is "
            "cherry-picking, not refinement.")


def refuse_dropped_points(expected_indices, recorded_indices) -> None:
    """Refuse a sweep record that is missing a planned point. Raises.

    Every planned point must appear in the record, whatever became of it: a
    safety-aborted, a settling-not-reached and a clipped-invalid point are
    all *kept*, because silently dropping the points that misbehaved is how a
    sweep is made to look cleaner than it was. A missing planned index is
    refused."""
    expected = set(int(i) for i in expected_indices)
    recorded = set(int(i) for i in recorded_indices)
    missing = sorted(expected - recorded)
    if missing:
        raise SweepError(
            f"refused: {len(missing)} planned sweep point(s) are missing from "
            f"the record: {missing}. Every planned point must be recorded -- "
            f"settling-not-reached, clipped and safety-aborted points are "
            f"kept, never dropped. A sweep that hides its bad points is not "
            f"honest.")


def refuse_synthetic_response_as_measurement(*_a, **_k) -> None:
    """Refuse a synthetic sweep response read as a physical measurement.

    Every response the controller collects is a ``SYNTHETIC_OBSERVATION`` --
    a number modelled from the swept parameters, reproducible from the seed,
    not transduced from a specimen. This delegates to the governance core's
    standing refusal."""
    C.refuse_synthetic_as_physical()


def refuse_feature_as_resonance(*_a, **_k) -> None:
    """Refuse a swept synthetic feature read as a physical resonance.

    The feature the adaptive refinement converges to is the Lorentzian this
    module PLANTED; there is no specimen and no measured resonance. Delegates
    to the governance core's noise/feature refusal."""
    C.refuse_noise_as_resonance()


# =======================================================================
# The report
# =======================================================================

def _demo_setup():
    """Build the worked demonstration: a frozen protocol, a base config, a
    frequency sweep around a planted resonance, and a synthetic model."""
    sealed_proto = P.example_seal()
    authorized = frozenset(sealed_proto.protocol.required_capabilities())
    base_config = PR.RunConfig(
        specimen_id="SYN_SPECIMEN_0", fixture_id="SYN_FIXTURE_0",
        calibration_id="SYN_CAL_0", authorized_capabilities=authorized,
        mode=PR.ExecutionMode.SYNTHETIC, seed=20260724,
        environment={"T_K": 300.0, "note": "synthetic sweep"},
        clock={"tick_hz": 1.0})
    feature = PlantedFeature(center_hz=1000.0, width_hz=25.0, height=1.0)
    model = SyntheticResponseModel(feature=feature)
    axis = linear_axis(SweepAxisKind.FREQUENCY, 800.0, 1200.0, 21,
                       unit="Hz", settle_time_s=0.5,
                       safety=SafetyBounds(0.0, 5000.0))
    plan = SweepPlan(
        plan_id="DEMO_SWEEP", axes=(axis,), strategy=SweepStrategy.ADAPTIVE,
        mode=SweepMode.SYNTHETIC, seed=20260724, dwell_s=1.0,
        adaptive=AdaptivePolicy(axis=SweepAxisKind.FREQUENCY,
                                max_refinements=12),
        lanes=("electrical", "clock_phase"))
    return sealed_proto, base_config, model, feature, plan


def sweep_report() -> dict:
    """The standing statement of what the controller is and is not.

    Runs a worked, deterministic demonstration: a frequency sweep around a
    planted 1000 Hz resonance collects all points, adaptive refinement
    converges toward the planted centre, a real sweep runs nothing, and a
    dropped-point record and a post-hoc adaptive refinement are both refused.
    Nothing here is measured."""
    sealed_proto, base_config, model, feature, plan = _demo_setup()
    sealed_plan = freeze(plan, epoch=20260724)
    controller = SweepController(sealed_plan, sealed_proto, base_config, model)
    result = controller.run(epoch=1000)
    result_again = controller.run(epoch=1000)

    # Determinism: same plan + seed => identical record.
    determinism = (r13_serialize.content_hash(result.to_record())
                   == r13_serialize.content_hash(result_again.to_record()))

    # Adaptive convergence toward the planted centre.
    est = result.feature_estimate
    converged = (est is not None
                 and abs(est["value"] - feature.center_hz) <= feature.width_hz)

    # A real sweep runs nothing.
    real_plan = replace(plan, plan_id="DEMO_REAL", strategy=SweepStrategy.LINEAR,
                        mode=SweepMode.REAL, adaptive=None)
    real_sealed = freeze(real_plan, epoch=1)
    real_ctrl = SweepController(real_sealed, sealed_proto, base_config, model)
    real_result = real_ctrl.run(epoch=1)
    real_is_unrun = all(
        r.status is PointStatus.PREREGISTERED_NOT_RUN for r in real_result.points)

    # A dropped point is refused.
    dropped_refused = False
    try:
        refuse_dropped_points(range(3), [0, 2])
    except SweepError:
        dropped_refused = True

    # A post-hoc adaptive refinement is refused.
    posthoc_refused = False
    try:
        refuse_adaptive_as_cherrypicking(None)
    except SweepError:
        posthoc_refused = True

    return {
        "what_this_is": (
            "an automated sweep controller: it walks a parameter grid "
            "(frequency, drive level, temperature setpoint, orientation) with "
            "linear, logarithmic, sparse, randomized or adaptive strategies, "
            "drives the P07 frozen protocol at every point to collect an "
            "ExperimentRun, orders a randomized traversal with the P08 "
            "engine, applies settling, safety-bound and clipping policies, "
            "records every point (nothing dropped), refines adaptively only "
            "when pre-declared, and supports checkpoint/resume without "
            "duplicating evidence"),
        "strategies": [s.value for s in SweepStrategy],
        "modes": [m.value for m in SweepMode],
        "axis_kinds": [k.value for k in SweepAxisKind],
        "point_statuses": [s.value for s in PointStatus],
        "planted_feature": {"center_hz": feature.center_hz,
                            "width_hz": feature.width_hz},
        "n_planned": result.n_planned,
        "n_recorded": len(result.points),
        "status_counts": result.status_counts(),
        "feature_estimate": est,
        "adaptive_converged_to_planted_centre": converged,
        "determinism_same_seed": determinism,
        "real_sweep_runs_nothing": real_is_unrun,
        "dropped_point_refused": dropped_refused,
        "posthoc_adaptive_refused": posthoc_refused,
        "refusals": [
            "refuse_adaptive_as_cherrypicking",
            "refuse_dropped_points",
            "refuse_synthetic_response_as_measurement",
            "refuse_feature_as_resonance",
        ],
        "claim_class": SOFTWARE_CLAIM_CLASS.value,
        "point_claim_class": POINT_CLAIM_CLASS.value,
        "software_ceiling": C.MAX_SOFTWARE_CLASS.value,
        "measured_here": MEASURED_HERE,
        "physical_validation": PHYSICAL_VALIDATION,
        "physical_sweep_status": PHYSICAL_SWEEP_STATUS,
        "verdict": VERDICT,
        "what_this_does_not_say": (
            "It does not measure anything. Every synthetic sweep point drives "
            "a seeded deterministic simulator and yields a "
            "SYNTHETIC_OBSERVATION -- reproducible from the seed and never a "
            "PHYSICAL_MEASUREMENT. The feature the adaptive refinement "
            "converges to is the Lorentzian this module PLANTED, not a "
            "measured resonance. A REAL sweep is not performed at all -- there "
            "is no apparatus in this environment -- so every point is recorded "
            "PREREGISTERED_NOT_RUN with no response. The controller records "
            "every planned point (settling-not-reached, clipped and "
            "safety-aborted points are kept, never dropped) and refuses "
            "adaptive refinement that was not pre-declared in the sealed plan. "
            "PHYSICAL_VALIDATION_NOT_CLAIMED."),
    }


__all__ = [
    "VERDICT", "MEASURED_HERE", "PHYSICAL_VALIDATION", "CONTROLLER_VERSION",
    "SOFTWARE_CLAIM_CLASS", "POINT_CLAIM_CLASS", "PHYSICAL_SWEEP_STATUS",
    "SweepError", "SweepAxisKind", "SweepStrategy", "SweepMode", "PointStatus",
    "VALID_STATUSES", "SafetyBounds", "SweepAxis",
    "linear_axis", "log_axis", "sparse_axis",
    "AdaptivePolicy", "SweepPlan", "SealedSweepPlan", "freeze",
    "SweepPoint", "ResponseSample", "SweepPointResult", "SweepResult",
    "PlantedFeature", "SyntheticResponseModel", "SweepController",
    "refuse_adaptive_as_cherrypicking", "refuse_dropped_points",
    "refuse_synthetic_response_as_measurement", "refuse_feature_as_resonance",
    "sweep_report",
]
