"""R10.15 Phase A03 — claim taxonomy, executable.

Seven classes. The ordering matters: a claim may never be promoted to
a stronger class by a computation alone. Simulation output is capped
at SIMULATED; only imported instrument data may be ESTABLISHED or
carry a measured value, and no software path in this package can
produce one.
"""

from __future__ import annotations

from enum import Enum

from rgcs_surface_wave import FORBIDDEN_CLAIM_TERMS


class ClaimClass(str, Enum):
    #: textbook physics with primary-source citation
    ESTABLISHED = "ESTABLISHED"
    #: exact analytic consequence of ESTABLISHED physics + declared inputs
    DERIVED = "DERIVED"
    #: numerical solver output under declared approximations
    SIMULATED = "SIMULATED"
    #: proposed but unverified relationship
    HYPOTHESIS = "HYPOTHESIS"
    #: reported by the source record; carries no physical warrant
    SOURCE_PROVENANCE = "SOURCE_PROVENANCE"
    #: a searched-for effect that was NOT found
    NULL = "NULL"
    #: result that needs independent reproduction before use
    REPLICATION_REQUIRED = "REPLICATION_REQUIRED"


#: Classes this software is permitted to emit. ESTABLISHED is reserved
#: for cited textbook physics, never generated by a solve.
SOFTWARE_EMITTABLE = frozenset({
    ClaimClass.DERIVED, ClaimClass.SIMULATED, ClaimClass.HYPOTHESIS,
    ClaimClass.SOURCE_PROVENANCE, ClaimClass.NULL,
    ClaimClass.REPLICATION_REQUIRED,
})

#: A measured force may only come from instrument intake, which this
#: package does not implement. Any attempt to label output as measured
#: is a policy violation.
MEASUREMENT_FORBIDDEN_NOTE = (
    "no measurement path exists in this package; instrument intake is "
    "not implemented and computed output is never a measurement")


class ClaimError(ValueError):
    """Raised when a claim would exceed its evidence."""


class Claim:
    """A statement with its evidence class, basis, and limitations."""

    def __init__(self, statement: str, claim_class: ClaimClass,
                 basis: str, limitations: list[str] | None = None):
        cc = ClaimClass(claim_class)
        if cc not in SOFTWARE_EMITTABLE and cc is not ClaimClass.ESTABLISHED:
            raise ClaimError(f"{cc} may not be emitted")
        low = statement.lower()
        for term in FORBIDDEN_CLAIM_TERMS:
            if term in low:
                raise ClaimError(
                    f"claim text contains the forbidden term {term!r}; "
                    "the evidence policy forbids it without physical "
                    "evidence, which this package cannot produce")
        if cc is ClaimClass.ESTABLISHED and not basis.strip():
            raise ClaimError("ESTABLISHED requires a primary-source basis")
        self.statement = statement
        self.claim_class = cc
        self.basis = basis
        self.limitations = list(limitations or [])

    def record(self) -> dict:
        return {"statement": self.statement,
                "claim_class": self.claim_class.value,
                "basis": self.basis, "limitations": self.limitations}

    def __repr__(self):
        return f"Claim({self.claim_class.value}: {self.statement[:48]!r})"


def assert_not_measurement(label: str) -> None:
    """Guard used by every force/field reporting path."""
    if "measur" in label.lower():
        raise ClaimError(
            f"refused: output labelled {label!r}. "
            + MEASUREMENT_FORBIDDEN_NOTE)


def taxonomy() -> dict:
    return {
        "schema": "rgcs.r1015.claim-taxonomy.v1",
        "classes": {
            "ESTABLISHED": "textbook physics with a primary source; "
                           "never produced by a solve in this package",
            "DERIVED": "exact analytic consequence of established "
                       "physics plus declared inputs",
            "SIMULATED": "numerical solver output under declared "
                         "approximations and convergence evidence",
            "HYPOTHESIS": "proposed relationship, not yet supported",
            "SOURCE_PROVENANCE": "reported by the source record only; "
                                 "carries no physical warrant",
            "NULL": "a searched-for effect that was not found, "
                    "published beside positive results",
            "REPLICATION_REQUIRED": "needs independent reproduction "
                                    "before any downstream use",
        },
        "promotion_rule": "no computation promotes a claim to a "
                          "stronger class; only new evidence can",
        "measurement_rule": MEASUREMENT_FORBIDDEN_NOTE,
    }
