"""Phyrll Generator Designer services: holder geometry derived from a
validated specimen, deterministic SCAD export, optional STL via external
OpenSCAD, and the build-sheet PDF.

Geometry rules (plan pack 04_MODULE_SPECS/PHYRLL_GENERATOR_DESIGNER.md):
cavity = specimen + 2 x clearance per axis; walls derived from cavity and
wall thickness; coil channel must fit inside the wall. Invalid parameter
combinations are refused with an explanation, never silently clamped.
"""
from __future__ import annotations

import math
import shutil
import subprocess
from pathlib import Path

from rgcs_desktop.services import pdf_sheets
from rgcs_desktop.services.design_studio import MODEL_OUTPUT, claim_boundary
from rgcs_desktop.services.export_receipts import make_receipt


class DesignError(ValueError):
    """A refused design parameter combination (with the reason)."""


def derive_holder_geometry(specimen: dict, params: dict) -> dict:
    """Cavity/wall geometry for a holder around ``specimen``.

    ``params``: clearance_mm (required), wall_thickness_mm (default 3),
    base_thickness_mm (default 4), coil_channel {enabled, width_mm,
    depth_mm}, holder_style, material, label_text.
    """
    clearance = params.get("clearance_mm")
    if clearance is None or not math.isfinite(float(clearance)):
        raise DesignError("clearance_mm is required and must be finite")
    clearance = float(clearance)
    if clearance < 0:
        raise DesignError(f"clearance_mm must be >= 0, got {clearance}")
    if clearance > 25:
        raise DesignError(
            f"clearance_mm {clearance} is implausibly large (> 25 mm); "
            f"refusing rather than printing a loose holder")

    wall = float(params.get("wall_thickness_mm", 3.0))
    base = float(params.get("base_thickness_mm", 4.0))
    if wall <= 0 or base <= 0:
        raise DesignError("wall/base thickness must be > 0")

    dims = specimen["dimensions"]
    length = float(dims["length_mm"])
    cross = float(dims.get("diameter_mm", dims.get("width_mm")))

    cavity_l = length + 2 * clearance
    cavity_w = cross + 2 * clearance
    geometry = {
        "cavity_length_mm": cavity_l,
        "cavity_width_mm": cavity_w,
        "cavity_depth_mm": cavity_w / 2.0,  # cradle: half-embedded
        "outer_length_mm": cavity_l + 2 * wall,
        "outer_width_mm": cavity_w + 2 * wall,
        "outer_height_mm": cavity_w / 2.0 + base,
        "wall_thickness_mm": wall,
        "base_thickness_mm": base,
    }

    channel = params.get("coil_channel") or {}
    if channel.get("enabled"):
        cw = float(channel.get("width_mm", 2.0))
        cd = float(channel.get("depth_mm", 1.5))
        if cw <= 0 or cd <= 0:
            raise DesignError("coil channel width/depth must be > 0")
        if cd >= wall:
            raise DesignError(
                f"coil channel depth {cd} mm does not fit inside the "
                f"{wall} mm wall; increase wall thickness or reduce depth")
        geometry["coil_channel"] = {"enabled": True, "width_mm": cw,
                                    "depth_mm": cd}
    else:
        geometry["coil_channel"] = {"enabled": False}
    return geometry


def render_scad(design: dict) -> str:
    """Deterministic OpenSCAD source for the holder design."""
    g = design["holder_geometry"]
    label = design.get("label_text", "")
    lines = [
        f"// RGCS Phyrll generator holder — design {design['design_id']}",
        f"// source specimen: {design['source_specimen_id']}",
        "// generated by rgcs_desktop.services.phyrll_generator "
        "(deterministic)",
        "// model output — an engineering plan, not a measurement",
        "",
        f"cavity_l = {g['cavity_length_mm']:.3f};",
        f"cavity_w = {g['cavity_width_mm']:.3f};",
        f"cavity_d = {g['cavity_depth_mm']:.3f};",
        f"outer_l = {g['outer_length_mm']:.3f};",
        f"outer_w = {g['outer_width_mm']:.3f};",
        f"outer_h = {g['outer_height_mm']:.3f};",
        f"wall = {g['wall_thickness_mm']:.3f};",
        f"base = {g['base_thickness_mm']:.3f};",
        "",
        "difference() {",
        "    // body",
        "    cube([outer_l, outer_w, outer_h]);",
        "    // crystal cavity (cradle)",
        "    translate([wall, wall, base])",
        "        cube([cavity_l, cavity_w, cavity_d + 0.01]);",
    ]
    ch = g.get("coil_channel", {})
    if ch.get("enabled"):
        lines += [
            "    // coil channel around the outside walls",
            f"    translate([-0.01, -0.01, base + cavity_d / 2 - "
            f"{ch['width_mm'] / 2:.3f}])",
            f"        difference() {{",
            f"            cube([outer_l + 0.02, outer_w + 0.02, "
            f"{ch['width_mm']:.3f}]);",
            f"            translate([{ch['depth_mm']:.3f}, "
            f"{ch['depth_mm']:.3f}, -0.01])",
            f"                cube([outer_l + 0.02 - "
            f"2 * {ch['depth_mm']:.3f}, outer_w + 0.02 - "
            f"2 * {ch['depth_mm']:.3f}, {ch['width_mm']:.3f} + 0.02]);",
            f"        }}",
        ]
    lines.append("}")
    if label:
        lines += [
            "",
            f'// label: {label}',
            f'translate([outer_l / 2, wall / 2, outer_h - 0.6])',
            f'    linear_extrude(0.6)',
            f'        text("{label}", size = 6, halign = "center");',
        ]
    return "\n".join(lines) + "\n"


def export_scad(design: dict, out_path: Path) -> dict:
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render_scad(design), encoding="utf-8")
    return make_receipt(
        inputs=design, outputs=[out_path],
        classification=MODEL_OUTPUT,
        object_id=design["design_id"],
        source_ids=[design["source_specimen_id"]],
        boundary=claim_boundary("build_sheet"))


def openscad_available() -> str | None:
    """Path to the OpenSCAD executable, or None."""
    return shutil.which("openscad")


def export_stl_if_available(scad_path: Path, out_path: Path) -> dict:
    """Render STL through external OpenSCAD when installed; otherwise
    return a status receipt marked unavailable (a stated absence, not an
    error — in-process STL rendering is deliberately not implemented)."""
    exe = openscad_available()
    scad_path, out_path = Path(scad_path), Path(out_path)
    if exe is None:
        return {"status": "unavailable",
                "reason": "OpenSCAD not installed; STL rendering requires "
                          "the external OpenSCAD CLI",
                "scad": scad_path.name, "outputs": []}
    out_path.parent.mkdir(parents=True, exist_ok=True)
    proc = subprocess.run([exe, "-o", str(out_path), str(scad_path)],
                          capture_output=True, text=True, timeout=300)
    if proc.returncode != 0 or not out_path.is_file():
        return {"status": "failed", "reason": proc.stderr[-2000:],
                "scad": scad_path.name, "outputs": []}
    receipt = make_receipt(inputs={"scad": scad_path.name},
                           outputs=[out_path],
                           classification=MODEL_OUTPUT,
                           boundary=claim_boundary("build_sheet"))
    receipt["status"] = "rendered"
    return receipt


#: Print settings included on every build sheet, by material.
PRINT_SETTINGS = {
    "PLA": {"nozzle_c": 210, "bed_c": 60, "layer_mm": 0.2, "infill": "30%",
            "walls": 3},
    "PETG": {"nozzle_c": 240, "bed_c": 80, "layer_mm": 0.2, "infill": "30%",
             "walls": 3},
    "ABS": {"nozzle_c": 250, "bed_c": 100, "layer_mm": 0.2, "infill": "30%",
            "walls": 4},
}


def render_build_sheet_pdf(design: dict, out_path: Path) -> dict:
    """Build sheet PDF: source, dimensions, print settings, generated
    files, claim boundary, hashes."""
    g = design["holder_geometry"]
    material = str(design.get("material", "PLA"))
    settings = PRINT_SETTINGS.get(material.upper(),
                                  PRINT_SETTINGS["PLA"])
    dim_rows = [(k.replace("_", " "), v) for k, v in sorted(g.items())
                if not isinstance(v, dict)]
    ch = g.get("coil_channel", {})
    if ch.get("enabled"):
        dim_rows += [("coil channel width (mm)", ch.get("width_mm")),
                     ("coil channel depth (mm)", ch.get("depth_mm"))]
    print_rows = [
        ("material", material),
        ("nozzle (°C)", settings["nozzle_c"]),
        ("bed (°C)", settings["bed_c"]),
        ("layer height (mm)", settings["layer_mm"]),
        ("infill", settings["infill"]),
        ("perimeter walls", settings["walls"]),
    ]
    exports = design.get("exports", {})
    file_rows = [(kind, name) for kind, name in sorted(exports.items())] \
        or [("SCAD", "not yet exported")]

    input_hash = pdf_sheets.sheet_input_hash(design)
    out_path = pdf_sheets.render_sheet_pdf(
        title="RGCS Engineering Build Sheet — Phyrll Generator Holder",
        subtitle=(f"Design {design['design_id']} · source specimen "
                  f"{design['source_specimen_id']}"),
        sections=[
            ("Dimensions (derived)", pdf_sheets.rows_block(dim_rows)),
            ("Print settings", pdf_sheets.rows_block(print_rows)),
            ("Generated files", pdf_sheets.rows_block(file_rows)),
            ("Measurement plan", pdf_sheets.paragraph(
                "Verify cavity fit against the physical specimen before "
                "winding coils; record actual clearances beside the "
                "design values.")),
        ],
        boundary=claim_boundary("build_sheet"),
        out_path=Path(out_path),
        input_hash=input_hash)
    return make_receipt(
        inputs=design, outputs=[out_path], classification=MODEL_OUTPUT,
        object_id=design["design_id"],
        source_ids=[design["source_specimen_id"]],
        boundary=claim_boundary("build_sheet"))
