"""OpenSCAD text export for specimen geometries (preview + file export).

Geometry math comes from rgcs_core; this module only renders SCAD source
text. Units: mm throughout (SCAD convention).
"""
from __future__ import annotations

from rgcs_core.geometry import (CrystalGeometry, SpiralGeometry,
                                crystal_geometry, spiral_curve)


def crystal_scad(g: CrystalGeometry) -> str:
    d = crystal_geometry(g)
    h_f = d["female_height_mm"]
    h_m = d["male_height_mm"]
    shaft = g.length_mm - h_f - h_m
    rot = 360.0 / (2 * g.facets) if g.diameter_mode == "across_flats" else 0.0
    # $fn = facets gives the prism; circumradius from the diameter mode.
    if g.diameter_mode == "across_vertices":
        r_w, r_n = g.wide_diameter_mm / 2, g.narrow_diameter_mm / 2
    else:
        import math
        c = math.cos(math.pi / g.facets)
        r_w, r_n = g.wide_diameter_mm / 2 / c, g.narrow_diameter_mm / 2 / c
    return f"""// RGCS v2 crystal specimen — generated by rgcs_desktop
// female (wide) apex at z=0, male (narrow) apex at z={g.length_mm:.4f}
// L={g.length_mm} mm, D_w={g.wide_diameter_mm} mm, D_n={g.narrow_diameter_mm} mm,
// N_f={g.facets}, angles {g.female_angle_deg}/{g.male_angle_deg} deg ({g.angle_mode})
// NOTE: default angles 51.843/60 deg are a Source claim (RG-16).
$fn = {g.facets};
rotate([0, 0, {rot:.4f}]) union() {{
    // female termination (wide apex)
    translate([0, 0, {h_f:.4f}]) mirror([0, 0, 1])
        cylinder(h = {h_f:.4f}, r1 = 0, r2 = {r_w:.4f});
    // frustum shaft
    translate([0, 0, {h_f:.4f}])
        cylinder(h = {shaft:.4f}, r1 = {r_w:.4f}, r2 = {r_n:.4f});
    // male termination (narrow apex)
    translate([0, 0, {h_f + shaft:.4f}])
        cylinder(h = {h_m:.4f}, r1 = {r_n:.4f}, r2 = 0);
}}
"""


def spiral_scad(g: SpiralGeometry, samples: int = 400,
                wire_radius_mm: float = 1.0) -> str:
    c = spiral_curve(g, samples=samples)
    pts = "\n".join(
        f"    translate([{x:.3f}, {y:.3f}, {z:.3f}]) sphere(r = {wire_radius_mm});"
        for x, y, z in zip(c["x"], c["y"], c["z"]))
    return f"""// RGCS v2 spiral-cone resonator path — generated by rgcs_desktop
// q={g.q_per_turn:.6f}, T={g.turns}, R_0={g.outer_radius_mm} mm, H={g.height_mm} mm,
// p_z={g.cone_exponent}, Omega_s={g.phase_winding}
// Path rendered as hulled sphere chain (preview quality).
$fn = 16;
module path_point(i) {{}}
union() {{
{pts}
}}
"""
