"""P09 — the vortex/glyph grammar, and what it actually is.

The source material presents a doubling cycle on digital roots --
1, 2, 4, 8, 7, 5 repeating, with 3, 6 and 9 standing outside it -- as
a fundamental structure, often with the 3-6-9 set singled out as
special.

The pattern is real. Every step of it is correct arithmetic. What it
is, exactly:

    The digital root of n in base b is n mod (b - 1). In base 10 that
    is mod 9. Doubling repeatedly is then the cyclic subgroup
    generated by 2 in the integers mod 9. Its order is 6, giving the
    six-element cycle. 3 and 6 sit outside it because they share a
    factor with 9 and so are not in the multiplicative group at all;
    9 is 0.

That is the whole of it: the multiplicative order of 2 modulo 9.
Elementary group theory, entirely correct, and a hundred and fifty
years old.

**The decisive test is base generality.** If 3-6-9 were fundamental,
it would not depend on how many fingers we happen to have. It does.
Change base and the structure changes completely:

    base 10 (mod  9): cycle 1,2,4,8,7,5      excluded 3, 6
    base  8 (mod  7): cycle 1,2,4            excluded 3, 5, 6
    base 12 (mod 11): cycle 1,2,4,8,5,10,9,7,3,6   excluded nothing

In base 12 the cycle covers every nonzero residue and nothing is
excluded at all, because 2 is a primitive root modulo 11. The
"excluded trinity" is not a property of number. It is a property of
9 = 10 - 1 being composite, which is a property of our notation.

This module implements the pattern faithfully, proves it is what the
docstring says it is, and refuses claims that it is fundamental or
physical.
"""

from __future__ import annotations

from dataclasses import dataclass


class VortexClaimRefused(ValueError):
    """Raised when the doubling cycle is claimed as fundamental."""


def digital_root(n: int, base: int = 10) -> int:
    """Digital root of n: repeated digit-sum, equivalently n mod b-1.

    Returns b-1 rather than 0 for nonzero multiples, matching the
    classical convention where the digital root of 9 is 9.
    """
    if base < 2:
        raise ValueError(f"base must be at least 2, got {base}")
    if n < 0:
        raise ValueError(f"digital root is defined for n >= 0, got {n}")
    if n == 0:
        return 0
    r = n % (base - 1)
    return r if r else base - 1


def digit_sum(n: int, base: int = 10) -> int:
    if base < 2:
        raise ValueError(f"base must be at least 2, got {base}")
    if n < 0:
        raise ValueError("n must be non-negative")
    s = 0
    while n:
        s += n % base
        n //= base
    return s


def is_cyclic_base(base: int) -> bool:
    """Is 2 a unit mod (base-1)?

    Only then is the doubling trajectory from 1 a genuine cycle and
    the multiplicative-order identification valid. True exactly when
    the base is even.
    """
    from math import gcd
    return gcd(2, base - 1) == 1


def doubling_trajectory(start: int = 1, base: int = 10) -> list[int]:
    """Distinct values visited by repeated doubling, in order.

    For odd bases this is a "rho": a tail leading into a loop, not a
    cycle. Use :func:`doubling_cycle` when a genuine cycle is required.
    """
    m = base - 1
    if m < 1:
        raise ValueError(f"base must be at least 2, got {base}")
    seq: list[int] = []
    x = start % m or m
    seen = set()
    while x not in seen:
        seen.add(x)
        seq.append(x)
        x = (x * 2) % m or m
    return seq


def doubling_cycle(start: int = 1, base: int = 10) -> list[int]:
    """The cycle generated by repeated doubling of digital roots.

    R9-D-010. This used to return the raw trajectory for any base and
    call it a cycle. For odd bases that is wrong: gcd(2, base-1) = 2,
    so 2 is not a unit, the trajectory from 1 never returns to 1, and
    the result is a tail leading into a loop. Base 11 returned
    ``[1, 2, 4, 8, 6]``, whose last element doubles to 2 rather than
    back to 1 -- and ``multiplicative_order(2, 10)`` is 0, so the
    module's headline identification (cycle length = order of 2) was
    silently false there.

    It was invisible because ``COMPARISON_BASES`` happened to contain
    only even bases. The identification is real; its scope was not
    stated. Odd bases are now refused explicitly rather than answered
    wrongly.
    """
    if not is_cyclic_base(base):
        raise ValueError(
            f"base {base} is odd, so gcd(2, {base - 1}) = 2 and 2 is "
            f"not a unit mod {base - 1}. Doubling from 1 never returns "
            f"to 1: the trajectory is a tail into a loop, not a cycle, "
            f"and the multiplicative-order identification does not "
            f"apply. Use doubling_trajectory() if you want the raw "
            f"orbit.")
    return doubling_trajectory(start, base)


def excluded_residues(base: int = 10) -> list[int]:
    """Nonzero residues below the modulus that doubling never reaches.

    This ranges over 1..m-1 and so can never return m itself. In base
    10 it returns [3, 6], not [3, 6, 9]: 9 is congruent to 0 mod 9 and
    is excluded for a third reason again, being the additive identity
    rather than a unit the orbit misses. See
    :func:`excluded_including_modulus` for the popular framing.
    """
    m = base - 1
    return sorted(set(range(1, m)) - set(doubling_cycle(1, base)))


def excluded_including_modulus(base: int = 10) -> list[int]:
    """The popular "3, 6 and 9" list, with the modulus included.

    R9-D-019: the module's narrative said "3, 6 and 9 stand outside"
    while every computed artefact returned only [3, 6], because 9 was
    handled in prose alone. It is a genuinely different case, so it is
    now returned explicitly and labelled rather than left to the
    reader to reconcile.
    """
    return excluded_residues(base) + [base - 1]


def exclusion_mechanisms(base: int = 10) -> dict:
    """Residues are excluded for **two different reasons**, and they
    must not be run together (R9-D-005).

    1. **Non-units.** gcd(a, m) > 1, so a is not in the multiplicative
       group at all and no power of anything coprime reaches it. This
       is why 3 and 6 are excluded mod 9.
    2. **Units outside the orbit.** a is a unit, but not in the cyclic
       subgroup generated by 2. This is why 3, 5 and 6 are excluded
       mod 7 -- and 7 is *prime*, so mechanism 1 contributes nothing
       there.

    The base-8 case is the counterexample that keeps both mechanisms
    honest: a prime modulus does not imply an empty exclusion set.
    For the exclusion set to be empty you need **both** m prime (no
    non-units) **and** 2 a primitive root mod m (the orbit covers
    every unit). Base 12 satisfies both. Base 8 satisfies only the
    first.
    """
    from math import gcd
    m = base - 1
    units = {a for a in range(1, m) if gcd(a, m) == 1}
    orbit = set(doubling_cycle(1, base))
    non_units = sorted(set(range(1, m)) - units)
    units_outside_orbit = sorted(units - orbit)
    return {
        "base": base,
        "modulus": m,
        "modulus_is_prime": all(m % d for d in range(2, int(m ** 0.5) + 1))
                            and m > 1,
        "excluded_as_non_units": non_units,
        "excluded_as_units_outside_orbit": units_outside_orbit,
        "two_is_primitive_root": bool(units) and orbit == units,
        "excluded_total": sorted(set(non_units) | set(units_outside_orbit)),
        "note": (
            "these are different mechanisms and conflating them gets "
            "the base-12 explanation wrong in both directions: "
            "'2 is a primitive root' alone does not explain it "
            "(you also need no non-units), and 'the modulus is prime' "
            "alone does not either (base 8 is prime and still excludes "
            "three residues)"),
    }


def multiplicative_order(a: int, m: int) -> int:
    """Order of a in the multiplicative group mod m, or 0 if a is not
    a unit (which is precisely why 3 and 6 are 'excluded' mod 9)."""
    from math import gcd
    if gcd(a, m) != 1:
        return 0
    k, x = 1, a % m
    while x != 1:
        x = (x * a) % m
        k += 1
    return k


@dataclass(frozen=True)
class BaseStructure:
    """The doubling structure in one base."""

    base: int
    modulus: int
    cycle: tuple[int, ...]
    excluded: tuple[int, ...]

    @property
    def cycle_length(self) -> int:
        return len(self.cycle)

    @property
    def covers_everything(self) -> bool:
        return not self.excluded


def structure_in_base(base: int) -> BaseStructure:
    return BaseStructure(
        base=base,
        modulus=base - 1,
        cycle=tuple(doubling_cycle(1, base)),
        excluded=tuple(excluded_residues(base)),
    )


#: Bases compared in the base-generality test. 12 is the decisive one.
COMPARISON_BASES = (6, 8, 10, 12, 16)


def base_generality_test() -> dict:
    """The falsifiable test: is the structure base-independent?

    It is not, and this is not a close call.
    """
    structures = {b: structure_in_base(b) for b in COMPARISON_BASES}
    cycle_lengths = {b: s.cycle_length for b, s in structures.items()}
    fully_covering = [b for b, s in structures.items()
                      if s.covers_everything]
    return {
        "bases": list(COMPARISON_BASES),
        "structures": {
            b: {"modulus": s.modulus, "cycle": list(s.cycle),
                "excluded": list(s.excluded),
                "cycle_length": s.cycle_length}
            for b, s in structures.items()},
        "cycle_lengths": cycle_lengths,
        "base_independent": len(set(cycle_lengths.values())) == 1,
        "bases_with_nothing_excluded": fully_covering,
        "decisive_case": (
            "base 12: 11 is prime, so there are no non-units to "
            "exclude, AND 2 is a primitive root modulo 11, so the "
            "orbit covers every unit. Both conditions are needed and "
            "both hold, so nothing is excluded at all. There is no "
            "trinity to be found."),
        "why_both_conditions": (
            "base 8 is the counterexample that forces the care: 7 is "
            "prime, so there are no non-units, and yet 3, 5 and 6 are "
            "still excluded because the orbit of 2 covers only part of "
            "the unit group. Primality alone is not enough, and "
            "primitive-rootness alone is not enough (R9-D-005)."),
        "mechanisms": {b: exclusion_mechanisms(b)
                       for b in COMPARISON_BASES},
        "verdict": (
            "BASE_DEPENDENT: the cycle length, the members, and which "
            "residues are excluded all change with the base. A "
            "structure that changes when you change notation is a "
            "property of the notation."),
    }


def why_three_six_nine(base: int = 10) -> dict:
    """Why 3, 6 and 9 sit outside the base-10 cycle."""
    from math import gcd
    m = base - 1
    return {
        "base": base,
        "modulus": m,
        "excluded": excluded_residues(base),
        "reason_3_and_6": (
            f"gcd(3, {m}) = {gcd(3, m)} and gcd(6, {m}) = {gcd(6, m)}; "
            f"neither is coprime to {m}, so neither is a unit in the "
            f"multiplicative group and no power of 2 can reach them"),
        "reason_9": (
            "9 is congruent to 0 mod 9; it is the identity of the "
            "additive structure, not a member of the multiplicative "
            "group"),
        "order_of_2": multiplicative_order(2, m),
        "order_note": (
            f"the multiplicative order of 2 modulo {m} is "
            f"{multiplicative_order(2, m)}, which is exactly the "
            f"cycle length"),
        "group_theoretic_name": (
            "the cyclic subgroup generated by 2 in (Z/9Z)*, a group "
            "of order 6"),
        "status": "CORRECT_ARITHMETIC_ORDINARY_MATHEMATICS",
    }


def vortex_grammar_ledger() -> dict:
    """The P09 headline."""
    base10 = structure_in_base(10)
    return {
        "cycle_base_10": list(base10.cycle),
        "excluded_base_10": list(base10.excluded),
        "pattern_is_real": True,
        "pattern_is_correct": True,
        "what_it_is": why_three_six_nine(10),
        "base_generality": base_generality_test(),
        "verdict": (
            "The doubling cycle is real, exactly reproducible, and is "
            "the multiplicative order of 2 modulo 9. That is standard "
            "elementary number theory. It is not evidence of a hidden "
            "structure in nature, because it changes when the base "
            "changes, and nature does not know what base we write in."),
        "what_survives": (
            "The arithmetic survives completely and is worth keeping: "
            "digital roots, cyclic subgroups and multiplicative order "
            "are useful tools, and the cycle is a correct instance of "
            "them. Nothing about that requires the pattern to be "
            "fundamental in order to be true."),
        "what_does_not_survive": (
            "Any claim that 3, 6 and 9 are physically or "
            "cosmologically privileged. In base 12 nothing is excluded "
            "at all."),
        "evidence_class": "ARITHMETIC",
        "measured_here": "nothing",
        "novelty": "NONE",
        "prior_art": PRIOR_ART,
    }


#: Adversarial prior-art review, R9. Both halves of this analysis --
#: the unit-group identity and the base-dependence -- are already
#: published. This module is replication and exposition, not
#: discovery, and says so.
PRIOR_ART = (
    "Digital root = n mod (b-1) is centuries old (casting out nines). "
    "The identification of {1,2,4,5,7,8} as the unit group mod 9, with "
    "3, 6, 9 excluded for failing coprimality, is standard and "
    "published. The base-dependence critique is the standard published "
    "objection to 'vortex math' (RationalWiki; Chu-Carroll, Good "
    "Math/Bad Math, 2018), and systematic other-base exploration "
    "including base 12 has been published (theproblemsite.com). "
    "Novelty of this module: none. Its contribution is stating the "
    "mechanisms correctly and separating the two kinds of exclusion, "
    "which the popular critiques generally do not."
)


def refuse_fundamental_claim() -> None:
    """Refuse the doubling cycle as a fundamental or physical law."""
    t = base_generality_test()
    raise VortexClaimRefused(
        "the doubling cycle is the multiplicative order of 2 modulo "
        "9, not a fundamental structure. It is base dependent: in "
        f"base 12 nothing is excluded at all "
        f"(bases with nothing excluded: "
        f"{t['bases_with_nothing_excluded']}). The arithmetic is "
        "correct; the significance claim is not.")
