// RGCS Phyrll generator holder — design PHY-BASIC-001
// source specimen: CRY-NODES-001
// generated by rgcs_desktop.services.phyrll_generator (deterministic)
// model output — an engineering plan, not a measurement

cavity_l = 110.800;
cavity_w = 32.800;
cavity_d = 16.400;
outer_l = 116.800;
outer_w = 38.800;
outer_h = 20.400;
wall = 3.000;
base = 4.000;

difference() {
    // body
    cube([outer_l, outer_w, outer_h]);
    // crystal cavity (cradle)
    translate([wall, wall, base])
        cube([cavity_l, cavity_w, cavity_d + 0.01]);
    // coil channel around the outside walls
    translate([-0.01, -0.01, base + cavity_d / 2 - 1.000])
        difference() {
            cube([outer_l + 0.02, outer_w + 0.02, 2.000]);
            translate([1.500, 1.500, -0.01])
                cube([outer_l + 0.02 - 2 * 1.500, outer_w + 0.02 - 2 * 1.500, 2.000 + 0.02]);
        }
}

// label: PHY-BASIC-001
translate([outer_l / 2, wall / 2, outer_h - 0.6])
    linear_extrude(0.6)
        text("PHY-BASIC-001", size = 6, halign = "center");
