"""P09 — vortex/glyph grammar.

The pattern is reproduced faithfully first, then identified, then
tested for base independence. All three matter: getting the
arithmetic wrong would be as bad as overclaiming it.
"""

from __future__ import annotations

import pytest

from r9 import vortex as V


# --- the pattern is reproduced exactly --------------------------------

def test_base_10_cycle_is_the_familiar_one():
    assert V.doubling_cycle(1, 10) == [1, 2, 4, 8, 7, 5]


def test_three_and_six_are_excluded_in_base_10():
    assert V.excluded_residues(10) == [3, 6]


def test_digital_root_matches_repeated_digit_sum():
    """The closed form must agree with the naive definition."""
    for n in (0, 1, 9, 18, 99, 12345, 987654321):
        naive = n
        while naive >= 10:
            naive = V.digit_sum(naive, 10)
        assert V.digital_root(n, 10) == naive


def test_digital_root_of_nine_is_nine_not_zero():
    """Classical convention, and the tests below depend on it."""
    assert V.digital_root(9) == 9
    assert V.digital_root(18) == 9
    assert V.digital_root(0) == 0


def test_digital_root_works_in_other_bases():
    assert V.digital_root(7, 8) == 7
    assert V.digital_root(8, 8) == 1     # 8 = 10_8, digits sum to 1


def test_invalid_inputs_refused():
    with pytest.raises(ValueError):
        V.digital_root(-1)
    with pytest.raises(ValueError):
        V.digital_root(5, base=1)
    with pytest.raises(ValueError):
        V.digit_sum(-1)


# --- what the pattern is ----------------------------------------------

def test_cycle_length_is_the_multiplicative_order_of_two():
    """The identification, stated as an equality that could fail."""
    for base in V.COMPARISON_BASES:
        s = V.structure_in_base(base)
        order = V.multiplicative_order(2, s.modulus)
        assert s.cycle_length == order, f"base {base}"


def test_multiplicative_order_of_two_mod_nine_is_six():
    assert V.multiplicative_order(2, 9) == 6


def test_non_units_have_no_order_and_that_is_the_exclusion():
    """3 and 6 are excluded because they are not units mod 9 --
    the same fact stated two ways."""
    assert V.multiplicative_order(3, 9) == 0
    assert V.multiplicative_order(6, 9) == 0
    assert set(V.excluded_residues(10)) == {3, 6}


def test_explanation_names_the_group():
    w = V.why_three_six_nine(10)
    assert "cyclic subgroup generated by 2" in w["group_theoretic_name"]
    assert w["order_of_2"] == 6
    assert w["status"] == "CORRECT_ARITHMETIC_ORDINARY_MATHEMATICS"


# --- the decisive test -------------------------------------------------

def test_structure_is_not_base_independent():
    t = V.base_generality_test()
    assert not t["base_independent"]
    assert "BASE_DEPENDENT" in t["verdict"]


def test_two_exclusion_mechanisms_are_distinguished():
    """R9-D-005. Base 10 and base 8 exclude residues for completely
    different reasons, and the first version ran them together."""
    b10 = V.exclusion_mechanisms(10)
    assert b10["excluded_as_non_units"] == [3, 6]
    assert b10["excluded_as_units_outside_orbit"] == []

    b8 = V.exclusion_mechanisms(8)
    assert b8["excluded_as_non_units"] == []
    assert b8["excluded_as_units_outside_orbit"] == [3, 5, 6]


def test_a_prime_modulus_does_not_imply_nothing_is_excluded():
    """The counterexample that keeps both conditions honest: 7 is
    prime and base 8 still excludes three residues."""
    b8 = V.exclusion_mechanisms(8)
    assert b8["modulus_is_prime"]
    assert not b8["two_is_primitive_root"]
    assert b8["excluded_total"] == [3, 5, 6]


def test_empty_exclusion_needs_both_conditions():
    for base in V.COMPARISON_BASES:
        m = V.exclusion_mechanisms(base)
        empty = not m["excluded_total"]
        both = m["modulus_is_prime"] and m["two_is_primitive_root"]
        assert empty == both, f"base {base}"


def test_mechanisms_partition_the_exclusion_set():
    for base in V.COMPARISON_BASES:
        m = V.exclusion_mechanisms(base)
        assert set(m["excluded_total"]) == (
            set(m["excluded_as_non_units"])
            | set(m["excluded_as_units_outside_orbit"]))
        assert set(m["excluded_total"]) == set(V.excluded_residues(base))


def test_base_twelve_justification_names_both_conditions():
    t = V.base_generality_test()
    assert "11 is prime" in t["decisive_case"]
    assert "primitive root" in t["decisive_case"]
    assert "Both conditions are needed" in t["decisive_case"]
    assert "base 8" in t["why_both_conditions"]


def test_novelty_is_recorded_as_none():
    """Prior-art review found both halves already published."""
    L = V.vortex_grammar_ledger()
    assert L["novelty"] == "NONE"
    assert "casting out nines" in L["prior_art"]


def test_base_twelve_excludes_nothing():
    """If 3-6-9 were fundamental it would not depend on how many
    fingers we have. In base 12 there is no trinity at all."""
    s = V.structure_in_base(12)
    assert s.excluded == ()
    assert s.covers_everything
    assert s.cycle_length == 10
    assert 12 in V.base_generality_test()["bases_with_nothing_excluded"]


def test_cycle_lengths_differ_across_bases():
    t = V.base_generality_test()
    assert len(set(t["cycle_lengths"].values())) > 1


def test_every_cycle_is_a_genuine_cycle():
    """For even bases, doubling from 1 must return to 1.

    The stray `assert (c[-1] * 2) % m or m` that used to sit here
    parsed as `assert (expr or m)` and, since m >= 1 is always truthy,
    could never fail. Removed.
    """
    for base in V.COMPARISON_BASES:
        c = V.doubling_cycle(1, base)
        m = base - 1
        assert len(set(c)) == len(c)
        assert ((c[-1] * 2) % m or m) == c[0]


def test_odd_bases_are_refused_not_answered_wrongly():
    """R9-D-010. Base 11 returned [1,2,4,8,6] -- a tail into a loop,
    not a cycle -- and was labelled one. gcd(2,10) = 2, so 2 is not a
    unit and the order identification does not apply.
    """
    for base in (3, 5, 7, 9, 11, 13, 15, 17):
        assert not V.is_cyclic_base(base)
        with pytest.raises(ValueError) as e:
            V.doubling_cycle(1, base)
        assert "not a unit" in str(e.value)


def test_the_raw_trajectory_is_still_available_for_odd_bases():
    t = V.doubling_trajectory(1, 11)
    assert t == [1, 2, 4, 8, 6]
    # and it is demonstrably not a cycle
    assert (t[-1] * 2) % 10 != t[0]


def test_even_bases_are_exactly_the_cyclic_ones():
    for base in range(2, 30):
        assert V.is_cyclic_base(base) == (base % 2 == 0)


def test_identification_holds_across_all_even_bases():
    """Not just the five in COMPARISON_BASES -- the selection is what
    hid the odd-base failure in the first place."""
    for base in range(4, 40, 2):
        c = V.doubling_cycle(1, base)
        assert len(c) == V.multiplicative_order(2, base - 1), base


# --- claim discipline --------------------------------------------------

def test_ledger_affirms_the_arithmetic():
    """The pattern is not dismissed -- it is correct."""
    L = V.vortex_grammar_ledger()
    assert L["pattern_is_real"]
    assert L["pattern_is_correct"]
    assert "worth keeping" in L["what_survives"]


def test_ledger_rejects_the_significance_claim():
    L = V.vortex_grammar_ledger()
    assert "nature does not know what base we write in" in L["verdict"]
    assert "In base 12 nothing is excluded" in L["what_does_not_survive"]


def test_fundamental_claim_is_refused():
    with pytest.raises(V.VortexClaimRefused) as e:
        V.refuse_fundamental_claim()
    msg = str(e.value)
    assert "multiplicative order of 2 modulo" in msg
    assert "The arithmetic is\ncorrect" in msg or "arithmetic is" in msg


def test_ledger_claims_no_measurement():
    L = V.vortex_grammar_ledger()
    assert L["measured_here"] == "nothing"
    assert L["evidence_class"] == "ARITHMETIC"


def test_nine_is_returned_explicitly_not_only_in_prose():
    """R9-D-019. The narrative said '3, 6 and 9 stand outside' while
    every computed artefact returned [3, 6]."""
    assert V.excluded_residues(10) == [3, 6]
    assert V.excluded_including_modulus(10) == [3, 6, 9]


def test_nine_is_excluded_for_a_third_reason():
    """It is 0 mod 9 -- the additive identity, not a unit the orbit
    misses. Three distinct mechanisms, not one."""
    m = V.exclusion_mechanisms(10)
    assert 9 not in m["excluded_as_non_units"]
    assert 9 not in m["excluded_as_units_outside_orbit"]
    assert "congruent to 0" in V.why_three_six_nine(10)["reason_9"]
