"""P09 — vortex/glyph grammar.

The pattern is reproduced faithfully first, then identified, then
tested for base independence. All three matter: getting the
arithmetic wrong would be as bad as overclaiming it.
"""

from __future__ import annotations

import pytest

from r9 import vortex as V


# --- the pattern is reproduced exactly --------------------------------

def test_base_10_cycle_is_the_familiar_one():
    assert V.doubling_cycle(1, 10) == [1, 2, 4, 8, 7, 5]


def test_three_and_six_are_excluded_in_base_10():
    assert V.excluded_residues(10) == [3, 6]


def test_digital_root_matches_repeated_digit_sum():
    """The closed form must agree with the naive definition."""
    for n in (0, 1, 9, 18, 99, 12345, 987654321):
        naive = n
        while naive >= 10:
            naive = V.digit_sum(naive, 10)
        assert V.digital_root(n, 10) == naive


def test_digital_root_of_nine_is_nine_not_zero():
    """Classical convention, and the tests below depend on it."""
    assert V.digital_root(9) == 9
    assert V.digital_root(18) == 9
    assert V.digital_root(0) == 0


def test_digital_root_works_in_other_bases():
    assert V.digital_root(7, 8) == 7
    assert V.digital_root(8, 8) == 1     # 8 = 10_8, digits sum to 1


def test_invalid_inputs_refused():
    with pytest.raises(ValueError):
        V.digital_root(-1)
    with pytest.raises(ValueError):
        V.digital_root(5, base=1)
    with pytest.raises(ValueError):
        V.digit_sum(-1)


# --- what the pattern is ----------------------------------------------

def test_cycle_length_is_the_multiplicative_order_of_two():
    """The identification, stated as an equality that could fail."""
    for base in V.COMPARISON_BASES:
        s = V.structure_in_base(base)
        order = V.multiplicative_order(2, s.modulus)
        assert s.cycle_length == order, f"base {base}"


def test_multiplicative_order_of_two_mod_nine_is_six():
    assert V.multiplicative_order(2, 9) == 6


def test_non_units_have_no_order_and_that_is_the_exclusion():
    """3 and 6 are excluded because they are not units mod 9 --
    the same fact stated two ways."""
    assert V.multiplicative_order(3, 9) == 0
    assert V.multiplicative_order(6, 9) == 0
    assert set(V.excluded_residues(10)) == {3, 6}


def test_explanation_names_the_group():
    w = V.why_three_six_nine(10)
    assert "cyclic subgroup generated by 2" in w["group_theoretic_name"]
    assert w["order_of_2"] == 6
    assert w["status"] == "CORRECT_ARITHMETIC_ORDINARY_MATHEMATICS"


# --- the decisive test -------------------------------------------------

def test_structure_is_not_base_independent():
    t = V.base_generality_test()
    assert not t["base_independent"]
    assert "BASE_DEPENDENT" in t["verdict"]


def test_base_twelve_excludes_nothing():
    """If 3-6-9 were fundamental it would not depend on how many
    fingers we have. In base 12 there is no trinity at all."""
    s = V.structure_in_base(12)
    assert s.excluded == ()
    assert s.covers_everything
    assert s.cycle_length == 10
    assert 12 in V.base_generality_test()["bases_with_nothing_excluded"]


def test_cycle_lengths_differ_across_bases():
    t = V.base_generality_test()
    assert len(set(t["cycle_lengths"].values())) > 1


def test_every_cycle_is_a_genuine_cycle():
    """Whatever the base, doubling from 1 must return to 1."""
    for base in V.COMPARISON_BASES:
        c = V.doubling_cycle(1, base)
        m = base - 1
        assert len(set(c)) == len(c)
        assert (c[-1] * 2) % m or m
        assert ((c[-1] * 2) % m or m) == c[0]


# --- claim discipline --------------------------------------------------

def test_ledger_affirms_the_arithmetic():
    """The pattern is not dismissed -- it is correct."""
    L = V.vortex_grammar_ledger()
    assert L["pattern_is_real"]
    assert L["pattern_is_correct"]
    assert "worth keeping" in L["what_survives"]


def test_ledger_rejects_the_significance_claim():
    L = V.vortex_grammar_ledger()
    assert "nature does not know what base we write in" in L["verdict"]
    assert "In base 12 nothing is excluded" in L["what_does_not_survive"]


def test_fundamental_claim_is_refused():
    with pytest.raises(V.VortexClaimRefused) as e:
        V.refuse_fundamental_claim()
    msg = str(e.value)
    assert "multiplicative order of 2 modulo" in msg
    assert "The arithmetic is\ncorrect" in msg or "arithmetic is" in msg


def test_ledger_claims_no_measurement():
    L = V.vortex_grammar_ledger()
    assert L["measured_here"] == "nothing"
    assert L["evidence_class"] == "ARITHMETIC"
